myblog/urls.py
from django.urls import	path
from .import views
app_name	=	'myblog'

urlpatterns	=[
    # path('',views.post_list,name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:post_id>/share/',views.post_share,	name='post_share'),
    path('contact/',views.contact_us,	name='contact_us'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
]

myblogsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myblog.urls', namespace='myblog')),
]

myblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishedManager(models.Manager):
    def	get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES	=	(
        ('draft',	'Draft'),
        ('published',	'Published'),
        )
    title	=	models.CharField(max_length=250)
    slug	=	models.SlugField(max_length=250,unique_for_date='publish')
    author	=	models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body	=	models.TextField()
    publish	=	models.DateTimeField(default=timezone.now)
    created	=	models.DateTimeField(auto_now_add=True)
    updated	=	models.DateTimeField(auto_now=True)
    status	=	models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    objects	=	models.Manager()	#	The	default	manager.
    published = PublishedManager()	#	Our	custom	manager.
    def	get_absolute_url(self):
        return reverse('myblog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day,self.slug])
    class Meta:
        ordering	=	('-publish',)
    def	__str__(self):
        return	self.title

class Comment(models.Model):	
    post	=	models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name	=	models.CharField(max_length=80)	
    email	=	models.EmailField()	
    body	=	models.TextField()	
    created	=	models.DateTimeField(auto_now_add=True)	
    updated	=	models.DateTimeField(auto_now=True)	
    active	=	models.BooleanField(default=True)	
    class	Meta:	
        ordering	=	('created',)	
    def	__str__(self):	
        return 'Comment by {} on {}'.format(self.name, self.post)

class Contactus(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    message = models.TextField()
    create = models.DateTimeField(default=timezone.now)
    class	Meta:	
        ordering	=	('-create',)
    def	__str__(self):
        return	self.email

myblog/forms.py
from django	import forms
from .models	import	Comment, Contactus

class CommentForm(forms.ModelForm):
    class Meta:
        model	=	Comment
        fields	=	('name',	'email', 'body')

class ContactusForm(forms.ModelForm):
    class Meta:
        model	=	Contactus
        fields	=	('name',	'email', 'message')

class EmailPostForm(forms.Form):
    name	=	forms.CharField(max_length=25)
    email	=	forms.EmailField()
    to	=	forms.EmailField()
    comments	=	forms.CharField(required=False,widget=forms.Textarea)

myblog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post , Comment , Contactus
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from .forms	import	EmailPostForm , CommentForm , ContactusForm
from django.core.mail import send_mail

def	post_share(request,	post_id):
    post	=	get_object_or_404(Post,	id=post_id,	status='published') #	Retrieve	post	by	id
    sent =False
    if	request.method	==	'POST':    #	Form	was	submitted
        form	=	EmailPostForm(request.POST)
        if	form.is_valid():  #	Form	fields	passed	validation
            cd	=	form.cleaned_data 
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject	='{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message	='Read "{}"	at {}\n\n{}\'s comments:{}'.format(post.title, post_url,cd['name'],cd['comments'])
            send_mail(subject,	message, 'dubeyshivangi1910@gmail.com',[cd['to']])
            sent = True
            # print(sent)
    else:
        form	=	EmailPostForm()
    # print(sent)
    return	render(request,	'myblog/post/share.html',	{'post':	post,'form':	form,'sent':sent})


class PostListView(ListView):
    queryset	=	Post.published.all()
    context_object_name	=	'posts'
    paginate_by	=	5
    template_name	=	'myblog/post/list.html'

def	post_detail(request,year,month,day,post):
    post = get_object_or_404(Post,slug=post,status='published',publish__year=year,            publish__month=month,publish__day=day)
    comments	=	post.comments.filter(active=True)     
    new_comment	=	None
    if	request.method	==	'POST':                        
        comment_form = CommentForm(data=request.POST) 	
        if	comment_form.is_valid():   
            new_comment	=comment_form.save(commit=False) 
            new_comment.post	=	post             
            new_comment.save()             
    else:
        comment_form	=	CommentForm()
    return	render(request,'myblog/post/detail.html',{'post':	post, 'comments':	comments,'new_comment':	new_comment,'comment_form':	comment_form})

def contact_us(request):
    s = False
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactusForm(request.POST)
        
        # check whether it's valid:
        if form.is_valid():
            s = True
            form.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ContactusForm()

    return render(request, 'myblog/post/contact.html', {'form': form , 's':s})
# Create your views here.

myblog/templates/myblog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block	title %}{% endblock	%}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="{% static "css/myblog.css" %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar navbar-dark" style="background-color: #041F61;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><strong>My Blog Site</strong></a>
    </div>
    <ul class="nav navbar-nav">
	<a class="nav-link" href="{% url "myblog:post_list" %}"><i class="fa fa-home"></i> <strong>Home</strong><span class="sr-only">(current)</span></a>
      {% comment %} <li class="active"><a href="#">Home</a></li> {% endcomment %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
	
	<a class="nav-link" href="{% url "myblog:contact_us" %}"><i class="fa fa-phone"></i>  <strong>Contact Us</strong><span class="sr-only">(current)</span></a>
    </ul>
  </div>
</nav>
  

	{% comment %} <div id="content"> {% endcomment %}
	{% block content %}
	{% endblock %}
	{% comment %} </div> {% endcomment %}
	{% comment %} <div id="sidebar">
	<h2>My	blog</h2>
    <p>This	is	my	blog.</p> {% endcomment %}
	</div> 
</body>
</html>

myblog/templates/myblog/post/contact.html
{% extends "myblog/base.html" %}
{% block title %}Contact Us{% endblock %}
{% block content %}
<hr>
    <div class="container" id="con">
    <div style="background:lightskyblue !important" class="jumbotron" id =  "home">
      
{% comment %} print("dd")
print(post.sent) {% endcomment %}
    {% if s %}
        <h2>Thank you for contacting, Your Message is successfully Delivered!! We will contact you soon :)</h2>
    {% else	%}
        <h2><strong>CONTACT US</strong></h2>
        <hr width="500px">
        <form action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="button" type="submit" value="Submit">
        </form>
    {% endif %}
    </div>
    </div>
{% endblock %}

myblog/templates/myblog/post/detail.html
{% extends "myblog/base.html" %}
{% block title %} {{ post.title	}} {% endblock %}
{% block content %}
<hr>
    <div class="container" id="con">
    <div style="background:lightskyblue !important" class="jumbotron" id =  "home">
      
	<h2>{{ post.title }}</h2>
    <a href="{% url "myblog:post_share" post.id %}"> Share	this post 
    <i class="fa fa-share-alt" style="font-size:24px"></i>
    </a>
	<p class="date">
	Published {{ post.publish }} by	{{ post.author }}
    <hr width="600">
	</p> {{	post.body|linebreaks }}
    <hr style="height:2px;border-width:0;color:black;background-color:gray">

    {% with	comments.count as total_comments %}
		<h2>
				Total {{	total_comments	}}	comment{{	total_comments|pluralize	}} 
		</h2>
        <p  class="date"> To add new comment <i class="fa fa-angle-double-down" style="font-size:24px"></i>
</p>  
    {%	endwith	%}
    {%	for	comment	in	comments	%}
		<div	class="comment">
				
				<h2>{{	comment.body|linebreaks	}}</h2>
                <span id = "cmmnt">
						{% comment %} Comment	{{	forloop.counter	}} {% endcomment %}
                        	by	<strong>{{	comment.name	}}</strong>
						{{	comment.created	}}
				</span>
                <hr width="200">
		</div>
    {%	empty	%}
	    <p>There	are	no	comments	yet.</p>
    
    {%	endfor	%}
    
    </div>
    {% comment %} </div> {% endcomment %}
    </div>
    <div class="container" id="con">
    {% comment %} <div class="center"> {% endcomment %}
    <div style="background:mediumslateblue !important" class="jumbotron" id =  "home">
      
    {%	if	new_comment	%}
        <div class="alert alert-success">
        <h2><strong>Success!</strong> Your	comment	has	been	added.</h2>
        </div>
		
    {%	else	%}
		<h2>Add	a	new	comment</h2>
        <hr>
		<form	action="."	method="post">
				{{	comment_form.as_p	}}
				{%	csrf_token	%}
				<p><input class="button" type="submit"	value="Add	comment"></p>
		</form>
    {%	endif	%}
    </div>
    </div>
{% endblock %}

myblog/templates/myblog/post/list.html
{%	extends	"myblog/base.html" %}
{%	block title	%}My Blog{%	endblock %}
{%	block content %}
<button onclick="topFunction()" id="myBtn" title="Go to top">Back To Top</button>

   <div class="container" id="con">
    {% comment %} <div style="background:transparent !important" class="jumbotron"> {% endcomment %}
     
    <h1>Technical Blogs</h1>
    <div id="con1">{% include "pagination.html" with page=page_obj %}</div>
    {% comment %} </div> {% endcomment %}
        {% comment %} <hr> {% endcomment %}
    <div class="container">
    <div style="background:transparent" class="jumbotron">
        
        {% for post	in posts %}
            
            <div style="background:lightskyblue" class="jumbotron">
            <h2>
            <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
            </a>
            </h2>
            <a href="{% url "myblog:post_share" post.id %}"> Share	this post 
            <i class="fa fa-share-alt" style="font-size:24px"></i>
            </a>
            
            <p class="date">Published {{ post.publish }} by {{ post.author }} </p>
            <hr>
            {{ post.body|truncatewords:10|linebreaks }}
            
            </div>
        {%	endfor	%}
    </div>
    </div>
    
    </div>
    <script>
//Get the button
var mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
</script>

{%	endblock	%}

myblog/templates/myblog/post/share.html
{% extends "myblog/base.html" %}
{% block title %}Share	a	post{% endblock %}
{% block content %}
<hr>
    <div class="container" id="con">
    <div style="background:lightskyblue !important" class="jumbotron" id =  "home">
      
{% comment %} print("dd")
print(post.sent) {% endcomment %}
    {% if sent %}
        <h2>E-mail	successfully	sent</h2>
        <p>
            "{{	post.title	}}"	was	successfully	sent	to	{{ form.cleaned_data.to }}.
        </p>
    {% else	%}
        <h2>Share	"{{	post.title	}}"	by	e-mail</h2>
        <hr width="500px">
        <form action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="button" type="submit" value="Send e-mail">
        </form>
    {% endif %}
    </div>
    </div>
{% endblock %}

myblog/templates/pagination.html
<div class="pagination" id="con">
	<span class="step-links">
	{% if page.has_previous	%}
	<a id="next" href="?page={{ page.previous_page_number }}">Previous</a>
	{% endif %}
	<span	class="current"> Page {{ page.number }}	of	{{ page.paginator.num_pages	}}. </span>
	{% if page.has_next	%}
	<a id="next" href="?page={{ page.next_page_number }}">Next</a>
	{% endif %}
	</span>
</div>